### PR TITLE
filter discouraged status in EntitySuggester

### PR DESCRIPTION
**Pull request by Ptrhnk**

### CODE REVIEW

**Comment by davidzbiral** [comment]
@Ptrhnk Hey Petr, I forgot to add to this: also the Suggester should never suggest V entities. This was already implemented but for some reason it again suggests V entities. (This is because V entities are always new, e.g. age = V "23"  and amount of bottles = "23" should not connect these things.)

**Comment by Ptrhnk** [comment]
Ok, now when I started browsing history of suggester I found, that in january, status discouraged was put back but without possibility to add it to props (without the triangle icon) and sorted at the last place. 
There's your issue: #727

Screenshot 2022-07-19 at 18 00 28

**Comment by Ptrhnk** [comment]
The V excluding was missing in some suggesters so it's now fixed.

**Comment by davidzbiral** [comment]
@Ptrhnk : Yes please, reverse this. Sorry again.
The point on V entities remains valid.

**Pull request merged**
